name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 17 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.f938dca3e2ce4cbfbaaa427624902ee5 }}
          GP_TOKEN: ${{ secrets.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}}
          PUSH_TYPES: 'pushplus'
          PUSHPLUS_TOKEN: ${{ secrets.5d719082cbd943e689870d88caba977c }}
